version: '2.3'
services:
  lbds:
    stdin_open: true
    tty: true
    image: hzibraunschweig/lbds:${LBDS_JAR_FILE_VERSION}
    environment:
      - TZ=Europe/Berlin
      - LANG=de_DE.UTF-8
      - SPRING_PROFILES_ACTIVE=linkmobility,with-postgres
      - linkmobility_user=${LINKMOBILITY_USER}
      - linkmobility_password=${LINKMOBILITY_PASSWORD}
      - server_servlet_context_path=${LBDS_CONTEXT_PATH}
      - spring_datasource_username=${LBDS_POSTGRES_USER}
      - spring_datasource_password=${LBDS_POSTGRES_PASSWORD}
    links:
      - lbds-postgres:postgres
    ports:
      - 8080:8080/tcp

  lbds-postgres:
    image: postgres:13.1
    environment:
      - POSTGRES_USER=${LBDS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${LBDS_POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    stdin_open: true
    tty: true
    ports:
      - "127.0.0.1:5434:5432/tcp"