version: '2.3'

services:
  sormas:
    extends:
      file: services-base.yml
      service: base-sormas
    labels:
      - autoheal=true
        # override for stop timeout seconds during restart
      - autoheal.stop.timeout=30
    links:
      - postgres
    environment:
      - DB_JDBC_MAXPOOLSIZE=${DB_JDBC_MAXPOOLSIZE}
      - CUSTOMBRANDING_ENABLED=${CUSTOMBRANDING_ENABLED}
      - CUSTOMBRANDING_NAME=${CUSTOMBRANDING_NAME}
      - CUSTOMBRANDING_LOGO_PATH=${CUSTOMBRANDING_LOGO_PATH}
      - CUSTOMBRANDING_USE_LOGINSIDEBAR=${CUSTOMBRANDING_USE_LOGINSIDEBAR}
      - CUSTOMBRANDING_LOGINBACKGROUND_PATH=${CUSTOMBRANDING_LOGINBACKGROUND_PATH}
      - NAMESIMILARITYTHRESHOLD=${NAMESIMILARITYTHRESHOLD}
    volumes:
      - ${SORMAS_PATH}/documents:/opt/sormas/documents
      - ${SORMAS_PATH}/custom:/opt/sormas/custom
      - ${SORMAS_PATH}/sormas-logs:/opt/domains/sormas/logs
      - ${SORMAS_PATH}/sormas2sormas:/opt/sormas/sormas2sormas
    healthcheck:
      test: ["CMD", "curl", "-f", "-I", "http://localhost:6080/sormas-ui/login"]
      interval: 30s
      timeout: 7s
      retries: 3
      start_period: 300s
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    extends:
      file: services-base.yml
      service: base-postgres
    volumes:
      - ${SORMAS_PATH}/psqldata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pg_dump:
    extends:
      file: services-base.yml
      service: base-pg_dump
    environment:
      - DB_HOST=${DB_HOST}
      - PGPASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - POSTGRES_USER=${SORMAS_POSTGRES_USER}
      - BACKUP_FILES=${BACKUP_FILES}
      - BACKUP_PATH=${SORMAS_PATH}
    volumes:
      - /backup:/var/opt/db_dumps
      - ${SORMAS_PATH}:${SORMAS_PATH}
    depends_on:
      postgres:
        condition: service_healthy

  apache2:
    extends:
      file: services-base.yml
      service: base-apache2
    links:
      - sormas
    environment:
      - PROMETHEUS_SERVERS=${PROMETHEUS_SERVERS}
    volumes:
      - ./apache2/certs:/usr/local/apache2/certs
      - ${SORMAS_PATH}/apache2_log:/var/log/apache2
    ports:
      - 443:443
      - 80:80
    depends_on:
      sormas:
        condition: service_healthy

  autoheal:
    extends:
      file: services-base.yml
      service: base-autoheal
    environment:
        # wait 600 seconds before first health check
      - AUTOHEAL_START_PERIOD=600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock



  lbds:
    stdin_open: true
    tty: true
    image: hzibraunschweig/lbds:${LBDS_JAR_FILE_VERSION}
    environment:
      - TZ=Europe/Berlin
      - LANG=de_DE.UTF-8
      - SPRING_PROFILES_ACTIVE=linkmobility,with-postgres
      - linkmobility_user=${LINKMOBILITY_USER}
      - linkmobility_password=${LINKMOBILITY_PASSWORD}
      - server_servlet_context_path=${LBDS_CONTEXT_PATH}
      - spring_datasource_username=${LBDS_POSTGRES_USER}
      - spring_datasource_password=${LBDS_POSTGRES_PASSWORD}
    links:
      - lbds-postgres:postgres
    ports:
      - 127.0.0.1:8080:8080/tcp

  lbds-postgres:
    image: postgres:13.1
    environment:
      - POSTGRES_USER=${LBDS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${LBDS_POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    stdin_open: true
    tty: true
    ports:
      - "127.0.0.1:5434:5432/tcp"