version: '2.3'

services:
  base-sormas:
    restart: unless-stopped
    image: hzibraunschweig/sormas-application:${SORMAS_DOCKER_VERSION}
    environment:
      - SORMAS_POSTGRES_USER=${SORMAS_POSTGRES_USER}
      - SORMAS_POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - SORMAS_SERVER_URL=${SORMAS_SERVER_URL}
      - DB_HOST=${DB_HOST}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_JDBC_MAXPOOLSIZE=${DB_JDBC_MAXPOOLSIZE}
      - DB_NAME=${DB_NAME}
      - DB_NAME_AUDIT=${DB_NAME_AUDIT}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_FROM=${MAIL_FROM}
      - SORMAS_VERSION=${SORMAS_VERSION}
      - LOCALE=${LOCALE}
      - COUNTRY_NAME=${COUNTRY_NAME}
      - EPIDPREFIX=${EPIDPREFIX}
      - SEPARATOR=${SEPARATOR}
      - EMAIL_SENDER_ADDRESS=${EMAIL_SENDER_ADDRESS}
      - EMAIL_SENDER_NAME=${EMAIL_SENDER_NAME}
      - LATITUDE=${LATITUDE}
      - LONGITUDE=${LONGITUDE}
      - MAP_ZOOM=${MAP_ZOOM}
      - TZ=${TZ}
      - JVM_MAX=${APPSERVER_JVM_MAX}
      - GEO_UUID=${GEO_UUID}
      - DEVMODE=${DEVMODE}
      - JSON_LOGGING=${JSON_LOGGING}
      - GEO_TEMPLATE=${GEO_TEMPLATE}
      - GEO_LONG_TEMPLATE=${GEO_LONG_TEMPLATE}
      - GEO_LAT_TEMPLATE=${GEO_LAT_TEMPLATE}
      - CASEARCHIVEDAYS=${CASEARCHIVEDAYS}
      - EVENTARCHIVEDAYS=${EVENTARCHIVEDAYS}
    mem_limit: ${APPSERVER_MEM}
    mem_reservation: ${APPSERVER_MEM_RESERVED}
    healthcheck:
      test: ["CMD", "curl", "-f", "-I", "http://localhost:6080/sormas-ui/login"]
      interval: 30s
      timeout: 7s
      retries: 3
      start_period: 300s

  base-postgres:
    restart: unless-stopped
    labels:
      - autoheal=true
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    image: hzibraunschweig/sormas-postgres:${SORMAS_DOCKER_VERSION}
    environment:
      - POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_NAME_AUDIT=${DB_NAME_AUDIT}
      - SORMAS_POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - SORMAS_POSTGRES_USER=${SORMAS_POSTGRES_USER}
      - TZ=${TZ}
    mem_limit: ${DB_MEM}
    mem_reservation: ${DB_MEM_RESERVED}
    healthcheck:
      test: ["CMD", "psql", "-U", "${SORMAS_POSTGRES_USER}", "-c", "SELECT 1;", "${DB_NAME}"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s

  base-keycloak-postgres:
    restart: unless-stopped
    labels:
      - autoheal=true
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    image: hzibraunschweig/keycloak-postgres:${SORMAS_DOCKER_VERSION}
    environment:
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_DB=${KEYCLOAK_DB_NAME}
      - TZ=${TZ}
    cpus: 1.0
    mem_limit: ${KEYCLOAK_DB_MEM}
    mem_reservation: ${KEYCLOAK_DB_MEM_RESERVED}
    healthcheck:
      test: [ "CMD", "psql", "-U", "${KEYCLOAK_DB_USER}", "-c", "SELECT 1;", "${KEYCLOAK_DB_NAME}" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s

  base-pg_dump:
    restart: unless-stopped
    image: hzibraunschweig/sormas-pg-dump:${SORMAS_DOCKER_VERSION}
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_NAME_AUDIT=${DB_NAME_AUDIT}
      - PGPASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - SORMAS_POSTGRES_USER=${SORMAS_POSTGRES_USER}
      - TZ=${TZ}
      - MIN=15,45 # Twice the hour on 15 and 45 (use crontab notation)
      - HOUR= # Keep empty for every hour. Use crontab notation otherwise
      - KEEP=1 # keep db dumps for one day in backup folder
    cpus: ${DB_DUMP_CPUS}
    mem_limit: ${DB_DUMP_MEM}
    mem_reservation: ${DB_DUMP_MEM_RESERVED}

  base-apache2:
    restart: unless-stopped
    labels:
      - autoheal=true
    image: hzibraunschweig/sormas-apache2:${SORMAS_DOCKER_VERSION}
    environment:
      - SORMAS_SERVER_URL=${SORMAS_SERVER_URL}
      - TZ=${TZ}
    volumes:
      - ./apache2/certs:/usr/local/apache2/certs
      - ${SORMAS_PATH}/apache2_log:/var/log/apache2
    ports:
      - 443:443
      - 80:80
    cpus: ${WEBSERVER_CPUS}
    mem_limit: ${WEBSERVER_MEM}
    mem_reservation: ${WEBSERVER_MEM_RESERVED}
    healthcheck:
      test: ["CMD", "curl", "-f", "-I", "-k", "--resolve", "${SORMAS_SERVER_URL}:443:127.0.0.1", "https://${SORMAS_SERVER_URL}/downloads/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s

  base-autoheal:
    restart: unless-stopped
    image: willfarrell/autoheal:1.0.0
    environment:
        # watch all running containers.
      - AUTOHEAL_CONTAINER_LABEL=all
        # check every 10 seconds
      - AUTOHEAL_INTERVAL=10
        # wait 0 seconds before first health check
      - AUTOHEAL_START_PERIOD=600
        # Docker waits max 10 seconds (the Docker default) for a container to stop before killing
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
        # Unix socket for curl requests to Docker API
      - DOCKER_SOCK=/var/run/docker.sock
        # --max-time seconds for curl requests to Docker API
      - CURL_TIMEOUT=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  base-letsencrypt:
    restart: unless-stopped
    image: hzibraunschweig/sormas-letsencrypt:${SORMAS_DOCKER_VERSION}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - URL=${SORMAS_SERVER_URL}
      - EMAIL=${LETSENCRYPT_MAIL}
      - DISABLE_CERTBOT=${DISABLE_CERTBOT}
      - PROMETHEUS_SERVERS=${PROMETHEUS_SERVERS}
    volumes:
      - /var/lib/docker/letsencrypt-config:/config
      - ./letsencrypt/certs:/config/etc/letsencrypt/live
    ports:
      - 443:443
      - 80:80
    cpus: ${WEBSERVER_CPUS}
    mem_limit: ${WEBSERVER_MEM}
    mem_reservation: ${WEBSERVER_MEM_RESERVED}

  base-keycloak:
    restart: unless-stopped
    labels:
      - autoheal=true
    image: hzibraunschweig/sormas-keycloak:${SORMAS_DOCKER_VERSION}
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - DB_VENDOR=${KEYCLOAK_DB_VENDOR}
      - DB_DATABASE=${KEYCLOAK_DB_NAME}
      - DB_ADDR=${KEYCLOAK_DB_HOST}
      - DB_USER=${KEYCLOAK_DB_USER}
      - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=true
      - SORMAS_SERVER_URL=${SORMAS_SERVER_URL}
      - KEYCLOAK_SORMAS_UI_SECRET=${KEYCLOAK_SORMAS_UI_SECRET}
      - KEYCLOAK_SORMAS_REST_SECRET=${KEYCLOAK_SORMAS_REST_SECRET}
      - KEYCLOAK_SORMAS_BACKEND_SECRET=${KEYCLOAK_SORMAS_BACKEND_SECRET}
    cpus: ${KEYCLOAK_CPUS}
    mem_limit: ${KEYCLOAK_MEM}
    mem_reservation: ${KEYCLOAK_MEM_RESERVED}
    healthcheck:
      test: ["CMD", "curl", "-f", "-I", "http://localhost:8080/keycloak/auth/realms/master"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 300s
