#!/bin/bash

sed -i 's/${SORMAS_SERVER_URL}/'"${SORMAS_SERVER_URL}"'/' ${JBOSS_HOME}/SORMAS.json
sed -i 's/${KEYCLOAK_SORMAS_REST_SECRET}/'"${KEYCLOAK_SORMAS_REST_SECRET}"'/' ${JBOSS_HOME}/SORMAS.json
sed -i 's/${KEYCLOAK_SORMAS_UI_SECRET}/'"${KEYCLOAK_SORMAS_UI_SECRET}"'/' ${JBOSS_HOME}/SORMAS.json
sed -i 's/${KEYCLOAK_SORMAS_BACKEND_SECRET}/'"${KEYCLOAK_SORMAS_BACKEND_SECRET}"'/' ${JBOSS_HOME}/SORMAS.json

${JBOSS_HOME}/update-realm.sh &> /dev/null & disown