version: '3.8'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:${CENTRAL_KEYCLOAK_VERSION}
    env_file:
      - .env_keycloak
    volumes:
      - ./keycloak/data:/opt/jboss/keycloak/standalone/data/
    ports:
      - 8080:8080

  etcd:
    image: hzibraunschweig/central-etcd:${CENTRAL_DOCKER_VERSION}
    env_file:
      - .env_etcd
    volumes:
      - ./etcd/fixtures:/srv/fixtures
      - ./etcd/tls-setup/certs/:/srv/certs/
      - ./etcd/etcd.yml:/etc/etcd/etcd.yml:ro
    ports:
      - "4001:4001"
      - "2379:2379"
      - "2380:2380"

