#!/bin/bash
set -e

# Set up the database
echo "Starting database setup..."

psql -v ON_ERROR_STOP=1 --username "postgres" <<EOSQL
    CREATE USER ${SORMAS_POSTGRES_USER} WITH PASSWORD '${SORMAS_POSTGRES_PASSWORD}' CREATEDB;
    CREATE DATABASE ${DB_NAME} WITH OWNER = '${SORMAS_POSTGRES_USER}' ENCODING = 'UTF8';
    \c ${DB_NAME}
    CREATE OR REPLACE PROCEDURAL LANGUAGE plpgsql;
    ALTER PROCEDURAL LANGUAGE plpgsql OWNER TO ${SORMAS_POSTGRES_USER};
    CREATE EXTENSION pg_trgm;
    CREATE EXTENSION pgcrypto;
    CREATE EXTENSION pg_stat_statements;
    CREATE EXTENSION IF NOT EXISTS unaccent;
    GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO ${SORMAS_POSTGRES_USER};
EOSQL
